### ISSUE TITLE
S3 as storage backend

### ISSUE THREAD

**Issue by mfominov** [kochetkov-ma/allure-server#39]
Hi, thx for this project.

This is kind a feature request for storage retention.

Currently u use file system as data storage.
In k8s this can be persistent volume, ok.

Could u add feature to store reports on S3 and make it as options.
This feature will be helpful for people that have S3 but don't have persistence layer in k8s, or for HA option.

Thx.

**Comment by sahajamit** [comment]
Storing archived reports in s3 makes more sense. If we want alternate storage rather than the file system, it is better to use some DB like Postgres. The Enterprise edition of Allure also supports Postgres.

Once we start storing these results in Postgres then it would be really easy to plot a lot of other analytics.

Please confirm if this DB storage is in the future roadmap. Otherwise, I am planning to fork and build this capability.
